name: Flutter CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Flutter by using an official action
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      # Get Flutter dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # Run Dart Code Metrics
      - name: Run Dart Code Metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib/

      # Run Tests and Collect Coverage
      - name: Run Tests with Coverage
        run: flutter test --coverage

      # Generate HTML Report from coverage data
      - name: Generate HTML Report
        run: |
          sudo apt-get install lcov
          genhtml coverage/lcov.info -o coverage/html

      # Upload the coverage report as an artifact using version 3
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/html
